#!/bin/sh

if [ -z $XDG_CURRENT_DESKTOP ]; then
    export XDG_CURRENT_DESKTOP="stumpwm-GNOME-Flashback:GNOME-Flashback:GNOME"
fi

exec gnome-session --builtin --session=stumpwm-gnome-flashback --disable-acceleration-check "$@"
